# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples sources /etc/bash.bashrc).

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
#export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth
export HISTFILESIZE=9000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_colored_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b .DIR_COLORS`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'


#less options - raw control characters and no termcap initilization
#defined here so we can use it as an alias for less and for PAGER
LESS='/usr/bin/less -XR'
###
#aliases
###
#long human readable ls output
alias ll='ls -lh'

#grep with colors :)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

alias less=$LESS
alias more=less

#Alias vim to the windows version as it has utf support
#as the options getting it to work under cygwin are not
#nice
if [ -f c:/WINDOWS/gvim.bat ]; then
    alias gvim=c:/WINDOWS/gvim.bat
fi

#ruby documentation on the command line in color
alias ri='/usr/bin/ri --format ansi'

#ack-grep replacement of grep
alias ack=ack-grep

#use LESS as pager
export PAGER=$LESS

# ruby options
export RUBYOPT=rubygems

# i use vim if at all possible.
export EDITOR=vim
export GIT_EDITOR=vim

export JAVA_HOME=C:/java/jdk1.6.0_06/
export JDK_HOME=$JAVA_HOME

#make sure svn windows libraries come first.
export PATH=:C:/subversion/bin:$JAVA_HOME/bin:$PATH

#enable completion to work after settting up path as bash completion searches the 
#$PATH for it to work.

if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

#set higher up.  use this if not on a work station.
#export PS1='\[\e];\h <\u> \w \d \t\007\]\u@\h \w> '
#export PS1='\u@\h \w> '

#set up TimeZone
#export TZ=`cat /etc/timezone`

#ant output in color
export ANT_ARGS="-logger org.apache.tools.ant.listener.AnsiColorLogger"
export ANT_OPTS="-Dant.logger.defaults=$HOME/.antoptts"

export LANG=sv_SE.utf8
export LC_ALL=sv_SEutf8

